# vim: set ft=tmux:
############################################################
##           CUSTOM NORD TMUX THEME SETTINGS              ##
############################################################
# set BG=default to enable transparent
set -g @thm_bg "default"
# set -g @thm_bg "#2e3440"
set -g @thm_fg "#d8dee9"
set -g @thm_white "#e5e9f0"
set -g @thm_red "#bf616a"
set -g @thm_yellow "#ebcb8b"
set -g @thm_green "#a3be8c"
set -g @thm_teal "#94e2d5"
set -g @thm_cyan "#88c0d0"
set -g @thm_blue "#81a1c1"
set -g @thm_dgray "#3b4252"
set -g @thm_lgray "#4c566a"
set -g @thm_black "#2e3440"

mycpu_icon=" "
myram_icon=" "
folder_icon=" "
cmd_icon=" "
system_icon="󰣇 "
window_icon=" "
active_icon="󰔟"

HALF_ROUND_RIGHT=""
SEP_ROUND_RIGHT=""
HALF_ROUND_LEFT=""
SEP_ROUND_LEFT=""
TRIANGLE_LEFT=""
SEP_TRIANGLE_LEFT=""
TRIANGLE_RIGHT=""
SEP_TRIANGLE_RIGHT=""
HALF_SQUARE_RIGHT=""
SEP_SQUARE_RIGHT=""
HALF_SQUARE_LEFT="" 
SEP_SQUARE_LEFT=""

set -g status-style "bg=#{E:@thm_bg},fg=#{@thm_fg}"
set -g status-justify "centre"
set -g status-right-length 100
set -g status-left-length 100

set -g status-left "\
#[fg=#{@thm_cyan}]${HALF_ROUND_LEFT}\
#[bg=#{@thm_cyan},fg=#{@thm_black}]#{window_icon}\
#[bg=#{@thm_dgray},fg=default] #S \
#[fg=#{@thm_dgray},bg=default]#{HALF_ROUND_RIGHT} \
#[fg=#{@thm_dgray},bg=default]#{HALF_ROUND_LEFT}\
#[bg=#{@thm_dgray},fg=default]#{pane_current_path} \
#[bg=#{@thm_cyan},fg=#{@thm_black}] #{folder_icon}\
#[fg=#{@thm_cyan},bg=default]#{HALF_ROUND_RIGHT} \
#[fg=#{@thm_dgray},bg=default]#{HALF_ROUND_LEFT}\
#[bg=#{@thm_dgray},fg=default]#{pane_current_command} \
#[bg=#{@thm_cyan},fg=#{@thm_black}] #{cmd_icon}\
#[bg=default,fg=#{@thm_cyan}]#{HALF_ROUND_RIGHT}"

set -g status-right "\
#[fg=#{@thm_cyan},bg=default]#{HALF_ROUND_LEFT}\
#[bg=#{@thm_cyan},fg=#{@thm_black}]#{active_icon} \
#[bg=#{@thm_dgray},fg=default] #{t/f/%%H#:%%M:window_activity}\
#[fg=#{@thm_dgray},bg=default]#{HALF_ROUND_RIGHT} \
#[fg=#{@thm_blue}]#{HALF_ROUND_LEFT}\
#[bg=#{@thm_blue},fg=#{@thm_black}]#{mycpu_icon}\
#[bg=#{@thm_dgray},fg=#{@thm_blue}] #{cpu_percentage}\
#[fg=#{@thm_dgray},bg=default]#{HALF_ROUND_RIGHT} \
#[fg=#{@thm_lgray}]#{HALF_ROUND_LEFT}\
#[bg=#{@thm_lgray},fg=#{@thm_cyan}]#{myram_icon} \
#[bg=#{@thm_dgray},fg=default] #{ram_percentage} \
#[fg=#{@thm_dgray},bg=default]#{HALF_ROUND_RIGHT} \
#[fg=#{@thm_dgray}]#{HALF_ROUND_LEFT}\
#[bg=#{@thm_dgray},fg=#{@thm_yellow}]#{system_icon} \
#[bg=#{@thm_cyan},fg=#{@thm_black}] #h\
#[bg=default,fg=#{@thm_cyan}]#{HALF_ROUND_RIGHT}"

set -g window-status-format "\
#[fg=#{@thm_lgray}]${HALF_ROUND_LEFT}\
#[fg=#{@thm_cyan},bg=#{@thm_lgray}]#I \
#[fg=#{@thm_cyan},bg=#{@thm_dgray}] #W #F\
#[fg=#{@thm_dgray},bg=default]${HALF_ROUND_RIGHT}"

set -g window-status-current-format "\
#[fg=#{@thm_cyan}]${HALF_ROUND_LEFT}\
#[fg=#{@thm_black},bg=#{@thm_cyan}]#I \
#[fg=#{@thm_yellow},bg=#{@thm_dgray}] #W #F\
#[fg=#{@thm_dgray},bg=default]${HALF_ROUND_RIGHT}"

