# vim:set ft=tmux:
############################################################
##           CUSTOM NORD TMUX THEME SETTINGS              ##
############################################################
# set BG=default to enable transparent

mycpu_icon=" "
myram_icon=" "
folder_icon=" "
cmd_icon=" "
system_icon="󰣇 "
window_icon=" "
active_icon="󰔟 "

HALF_ROUND_RIGHT=""
SEP_ROUND_RIGHT=""
HALF_ROUND_LEFT=""
SEP_ROUND_LEFT=""
TRIANGLE_LEFT=""
SEP_TRIANGLE_LEFT=""
TRIANGLE_RIGHT=""
SEP_TRIANGLE_RIGHT=""
HALF_SQUARE_RIGHT=""
SEP_SQUARE_RIGHT=""
HALF_SQUARE_LEFT="" 
SEP_SQUARE_LEFT=""

set -g status-style "bg=black,fg=cyan"
set -g status-justify "centre"
set -g status-right-length 100
set -g status-left-length 100

set -g status-left "\
#[fg=teal]${HALF_ROUND_LEFT}\
#[bg=teal#,fg=cyan]#{window_icon} #S\
#[fg=teal]${SEP_ROUND_RIGHT}\
#[bg=blue]${HALF_ROUND_RIGHT} \
#[bg=blue#,fg=black]${folder_icon}#{pane_current_path}\
#[fg=blue]${SEP_ROUND_RIGHT}\
#[bg=cyan]${HALF_ROUND_RIGHT} \
#[bg=cyan#,fg=black]#{cmd_icon} #{pane_current_command}\
#[bg=default,fg=cyan]${HALF_ROUND_RIGHT}"

set -g status-right "\
#[fg=yellow#,bg=default]${HALF_ROUND_LEFT}\
#[bg=yellow#,fg=black]#{active_icon}#{t/f/%%H#:%%M:window_activity} \
#[fg=cyan]${HALF_ROUND_LEFT}\
#[bg=cyan#,fg=black]${mycpu_icon}#{cpu_percentage} \
#[fg=blue]${HALF_ROUND_LEFT}\
#[bg=blue#,fg=black]${myram_icon}#{ram_percentage} \
#[fg=teal]${HALF_ROUND_LEFT}\
#[bg=teal#,fg=cyan]#{system_icon}#h\
#[bg=black#,fg=teal]${HALF_ROUND_RIGHT}"

set -g window-status-format "\
#[fg=teal]${HALF_ROUND_LEFT}\
#[fg=default,bg=teal]#I: \
#[fg=default]#W #F\
#[fg=teal#,bg=default]${HALF_ROUND_RIGHT}"

set -g window-status-current-format "\
#[fg=yellow]${HALF_ROUND_LEFT}\
#[fg=black#,bg=yellow]#I: \
#[fg=black]#W #F\
#[fg=yellow#,bg=default]${HALF_ROUND_RIGHT}"
