unbind-key -a -T root

set -g status-position top
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g set-titles on
setw -g monitor-activity on
set -g focus-events on
set -g detach-on-destroy off
set -g mouse on
set -s escape-time 0
set -g history-limit 2000
set -g pane-border-lines "double"
# Set terminal options
# set -g default-terminal "tmux-256color"
set -g default-terminal "${TERM}"
set -as terminal-features ",*:RGB"
set -ga terminal-overrides ",xterm-256color:Tc"

# Set default shell
set -g default-shell "/bin/fish"
set -g @t-fzf-prompt "  "

bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind -n M-s choose-tree -s

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-S-Left resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up resize-pane -U 3
bind -n M-S-Down resize-pane -D 3

bind -n M-h split-window -v
bind -n M-v split-window -h

bind -n M-Enter new-window
bind -n M-c kill-pane
bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"

# Search sessions
bind -n C-e display-popup -E "\
tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
sed '/^$/d' | fzf --header 'Jump to session:' |\
xargs tmux switch-client -t"

# Search window in current session
bind -n M-f display-popup -E "\
tmux list-windows -F '#{window_index} #{window_name}' |\
sed '/^$/d' | fzf --header 'Jump to window:' |\
cut -d' ' -f1 |\
xargs tmux select-window -t"

source -F "#{d:current_file}/nord.conf"
# source -F "#{d:current_file}/catppuccin.conf"
# source -F "#{d:current_file}/syscolor.conf"

############################################################
##               TMUX PLUGINS THEME SETTINGS              ##
############################################################
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-cpu"
set -g @plugin "sainnhe/tmux-fzf"

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'
# set -g @continuum-save-interval '15'
run "~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux"
run "~/.config/tmux/plugins/tpm/tpm"
