import = [
  # "~/.config/alacritty/tokyo-night.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/nord.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
# TERM = "xterm-256color"
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# [[keyboard.bindings]]
# action = "Paste"
# key = "Y"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "Copy"
# key = "W"
# mods = "Alt"

[scrolling]
history = 100000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dimensions = { columns = 120, lines = 40 }
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.98
blur = true
dynamic_title = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
