[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
dim_foreground = "#8087a2"
bright_foreground = "#a9b1d6"

[colors.cursor]
text = "#1a1b26"
cursor = "#f4dbd6"

[colors.vi_mode_cursor]
text = "#1a1b26"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#1a1b26"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#1a1b26"
background = "#9ece6a"

[colors.footer_bar]
foreground = "#1a1b26"
background = "#a5adcb"

[colors.hints.start]
foreground = "#1a1b26"
background = "#e0af68"

[colors.hints.end]
foreground = "#1a1b26"
background = "#a5adcb"

[colors.selection]
text = "#1a1b26"
background = "#f4dbd6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#a5adcb"

[colors.dim]
black = "#494d64"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[[colors.indexed_colors]]
index = 16
color = "#f5a97f"

[[colors.indexed_colors]]
index = 17
color = "#f4dbd6"
